services:
  userinfo-backend:
    image: yvv4docker/userinfo-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - userinfo-network

  userinfo-frontend:
    image: yvv4docker/userinfo-frontend:latest
    ports:
      - "8080:8080"
    depends_on:
      - userinfo-backend
    env_file:
      - .env
    networks:
      - userinfo-network

networks:
  userinfo-network:
    driver: bridge
